### ISSUE TITLE
[IMPORTANT] Valid moves working but need adjustment

### ISSUE THREAD

**Issue by FabioMiguel2000** [FabioMiguel2000/LinesOfActions#5]
- On functions `move_vertical()` and `move_horizontal()`
- It is adding moves out of the board
- this can be critical for the AI when selecting moves

**Comment by RapaTachos** [comment]
on my way boss!!!
________________________________

**Comment by FabioMiguel2000** [comment]
@RapaTachos Please fix this issue, your are professional!
